version: '2'
services:
  hub:
    container_name: hub
    image: selenium/hub
    environment:
      - GRID_BROWSER_TIMEOUT=90000
      - GRID_TIMEOUT=100000
    ports:
      - '4444:4444'
    networks:
      selenium-network:
        aliases:
          - hub
  chrome:
    image: selenium/node-chrome
    links:
      - "hub:hub"
    external_links:
      - ifs-local-dev
    depends_on:
      - hub
    environment:
     - HUB_PORT_4444_TCP_ADDR=hub
      -HUB_PORT_4444_TCP_PORT=4444
    networks:
      - selenium-network
      - ifs_front-tier
networks:
  selenium-network:
    driver: bridge
  ifs_front-tier:
    external: true
