version: '3'
services:

  shib:
    image: innovateuk/ifs-shib-sp:0.5.2
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:443/Shibboleth.sso/Metadata"]
      interval: 15s
      timeout: 8s
    ports:
      - "443:443"
    environment:
      - "SPHOST=ifs.local-dev"
      - "IDPHOST=auth.local-dev:9443"
      - "HTTPSPORT=443"
      - "HTTPPORT=80"
    networks:
      ifs:
        aliases:
          - ifs.local-dev

  idp:
    image: innovateuk/ifs-shib-idp:0.5.2
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:9443/"]
      interval: 15s
      timeout: 8s
    ports:
      - "9443:9443"
    environment:
      - "SPHOST=ifs.local-dev"
      - "IDPHOST=auth.local-dev:9443"
      - "HTTPSPORT=9443"
      - "HTTPPORT=9080"
    networks:
      ifs:
        aliases:
          - auth.local-dev
          - iuk-auth-localdev

  ldap:
    image: innovateuk/ifs-ldap:0.4.0
    healthcheck:
      test: ["CMD", "ldapsearch", "-h", "localhost", "-p", "389", "-b", "dc=nodomain", "-x", "-LLL", "-s" "base"]
      interval: 15s
      timeout: 8s
    ports:
      - "389:389"
    environment:
      - "LDAPPORT=389"
    networks:
      ifs:

  application-svc:
    image: innovateuk/application-service:@version@
    healthcheck:
      test: ["CMD", "curl", "-f",  "http://localhost:8080/monitoring/health"]
      interval: 15s
      timeout: 8s
    networks:
      - ifs

  assessment-svc:
    image: innovateuk/assessment-service:@version@
    healthcheck:
      test: ["CMD", "curl", "-f",  "http://localhost:8080/assessment/monitoring/health"]
      interval: 15s
      timeout: 8s
    networks:
      - ifs

  competition-mgt-svc:
    image: innovateuk/competition-management-service:@version@
    healthcheck:
      test: ["CMD", "curl", "-f",  "http://localhost:8080/management/monitoring/health"]
      interval: 15s
      timeout: 8s
    networks:
      - ifs

  project-setup-mgt-svc:
    image: innovateuk/project-setup-management-service:@version@
    healthcheck:
      test: ["CMD", "curl", "-f",  "http://localhost:8080/project-setup-management/monitoring/health"]
      interval: 15s
      timeout: 8s
    networks:
      - ifs

  project-setup-svc:
    image: innovateuk/project-setup-service:@version@
    healthcheck:
      test: ["CMD", "curl", "-f",  "http://localhost:8080/project-setup/monitoring/health"]
      interval: 15s
      timeout: 8s
    networks:
      - ifs

  data-service:
    image: innovateuk/data-service:@version@
    healthcheck:
      test: ["CMD", "curl", "-f",  "http://localhost:8080/monitoring/health"]
      interval: 15s
      timeout: 8s
    networks:
      ifs:
        aliases:
          - ifs-data-service

networks:
  ifs:
    driver: bridge
