kind: ConfigMap
apiVersion: v1
metadata:
  name: web-config
data:
  SPRING_APPLICATION_JSON: '{"logout":{"url": "https://host.docker.internal:8443/Logout/"}}'
  IFS_WEB_REST_CONNECTIONS_MAX_TOTAL: "1000"
  IFS_WEB_REST_CONNECTIONS_MAX_PER_ROUTE: "1000"
  IFS_WEB_AJP_CONNECTIONS_MAX_TOTAL: "700"
  IFS_WEB_AJP_CONNECTIONS_ACCEPT_COUNT: "700"
  IFS_WEB_AJP_CONNECTIONS_MAX_THREADS: "300"
  IFS_LIVE_PROJECTS_LANDING_PAGE_URL: "host.docker.internal:8443"
  IFS_EARLY_METRICS_URL: "host.docker.internal:8443"
  IFS_WEB_BASEURL: 'https://host.docker.internal:8443'
  IFS_SHOW_COVID_QUESTIONNAIRE_LINKS: 'host.docker.internal:8443'
  IFS_LOANS_SALESFORCE_PAGE_URL: "https://loans-innovateuk.cs80.force.com/loansCommunity/s"
  IFS_EDI_SALESFORCE_PAGE_URL: "https://loans-innovateuk.cs80.force.com/EDI/s"