commonAnnotations:
  deployedWith: kustomize
  environment: perf

bases:
  - ../aws-base

components:
  - ../../../patches/new-relic-env-vars-patch
  - ../../../patches/pull-secrets-patch
  - ../../../patches/spring-profile-patch
  - ../../../patches/wait-for-db-patch

resources:
  - config-maps/spring-config.yml

patchesStrategicMerge:
  - data-layer/data-service/data-service-deployment.yml
  - web-layer/registration-service/registration-service-deployment.yml