apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

components:
  - ../../patches/pull-secrets-patch

resources:
  # data service
  - data-service/data-service.yml
  - data-service/data-service-deployment.yml
  # data service alerts
  - data-service-alerts/data-service-alerts.yml
  - data-service-alerts/data-service-alerts-deployment.yml
  # finance data service
  - finance-data-service/finance-data-service.yml
  - finance-data-service/finance-data-service-deployment.yml
  # survey data service
  - survey-data-service/survey-data-service.yml
  - survey-data-service/survey-data-service-deployment.yml
