apiVersion: apps/v1
kind: Deployment
metadata:
  name: survey-data-svc
  annotations:
    monitor: monitor
    waitForDb: waitForDb
    javaDebug: javaDebug
    pullSecrets: pullSecrets
    waitForDs: waitForDs
    slow: slow
    newRelic: newRelic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: survey-data-svc
  template:
    metadata:
      labels:
        app: survey-data-svc
    spec:
      containers:
      - image: survey-data-service
        name: spring-boot-service-container
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command: [ "/bin/sh", "-c", "echo 'terminating pod' >> /proc/1/fd/1" ]
        livenessProbe:
          httpGet:
            path: /monitoring/health
            port: 8080
          initialDelaySeconds: 100
          periodSeconds: 31
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /monitoring/health
            port: 8080
          initialDelaySeconds: 100
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 1
        envFrom: []
        env:
          - name: SPRING_DATASOURCE_URL
            valueFrom:
              secretKeyRef:
                name: survey-data-service-secrets
                key: DB_URL
          - name: SPRING_FLYWAY_URL
            valueFrom:
              secretKeyRef:
                name: survey-data-service-secrets
                key: DB_URL
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: survey-data-service-secrets
                key: DB_USER
          - name: SPRING_FLYWAY_USER
            valueFrom:
              secretKeyRef:
                name: survey-data-service-secrets
                key: DB_USER
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: survey-data-service-secrets
                key: DB_PASS
          - name: SPRING_FLYWAY_PASSWORD
            valueFrom:
              secretKeyRef:
                name: survey-data-service-secrets
                key: DB_PASS
          - name: SPRING_DATASOURCE_TOMCAT_MAX_ACTIVE
            valueFrom:
              configMapKeyRef:
                name: data-service-config
                key: SPRING_DATASOURCE_TOMCAT_MAX_ACTIVE
          - name: IFS_WEB_SYSTEM_USER_UID
            valueFrom:
              secretKeyRef:
                name: web-secrets
                key: IFS_WEB_SYSTEM_USER_UID
          - name: JAVA_TOOL_OPTIONS
            value: -Xms800m -Xmx800m -javaagent:/newrelic.jar
          - name: NEW_RELIC_APP_NAME
            value: 'ifs-$(NEW_RELIC_ENV)-survey-data-service'
        ports:
          - containerPort: 8080
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 100m
            memory: 400M

