kind: ConfigMap
apiVersion: v1
metadata:
  name: data-service-config
data:
  DATA_SERVICE_HOST: "${DATA_SERVICE_HOST}"
  DATA_SERVICE_PORT: "${DATA_SERVICE_PORT}"
  IDP_REST_BASEURL: 'http://registration-svc:8080'
  SPRING_DATASOURCE_TOMCAT_MAX_ACTIVE: '100'
  IFS_DATA_SERVICE_FILE_GRANT_SEND_DELAY_MILLIS: "${IFS_DATA_SERVICE_FILE_GRANT_SEND_DELAY_MILLIS}"
  IFS_FINANCE_TOTALS_ENABLED: "${IFS_FINANCE_TOTALS_ENABLED}"
  IFS_FINANCE-TOTALS_AUTHSECRETKEY: "${AUTH_KEY}"
  SIL_REST_BASEURL: "${SIL_REST_BASEURL}"
  IFS_DATA_POSTCODE_LOOKUP_KEY: "${IFS_DATA_POSTCODE_LOOKUP_KEY}"
  IFS_DATA_COMPANIES_HOUSE_KEY: "${IFS_DATA_COMPANIES_HOUSE_KEY}"
  IFS_DATA_SERVICE_FILE_STORAGE_BASE: "${IFS_DATA_SERVICE_FILE_STORAGE_BASE}"
  IFS_SYSTEM_INTERNAL_USER_EMAIL_DOMAIN: "${IFS_SYSTEM_INTERNAL_USER_EMAIL_DOMAIN}"
  IFS_SYSTEM_INTERNAL_USER_EMAIL_DOMAINS: "${IFS_SYSTEM_INTERNAL_USER_EMAIL_DOMAINS}"
  IFS_SYSTEM_EXTERNAL_USER_EMAIL_DOMAIN: "${IFS_SYSTEM_EXTERNAL_USER_EMAIL_DOMAIN}"
