kind: ConfigMap
apiVersion: v1
metadata:
  name: feature-toggle-config
data:
  IFS_SUPPORTER_ENABLED: "${IFS_SUPPORTER_ENABLED}"
  IFS_SUBSIDY_CONTROL_ENABLED: "${IFS_SUBSIDY_CONTROL_ENABLED}"
  IFS_NEW_ORGANISATION_SEARCH_ENABLED: "${IFS_NEW_ORGANISATION_SEARCH_ENABLED}"
  IFS_PROCUREMENT_MILESTONES_ENABLED: "${IFS_PROCUREMENT_MILESTONES_ENABLED}"
  IFS_SUBSIDY_CONTROL_NORTHERN_IRELAND_ENABLED: "${IFS_SUBSIDY_CONTROL_NORTHERN_IRELAND_ENABLED}"
  IFS_KTP_FEC_FINANCE_MODEL_ENABLED: "${IFS_KTP_FEC_FINANCE_MODEL_ENABLED}"