kind: ConfigMap
apiVersion: v1
metadata:
  name: shibboleth-config
data:
  SHIBBOLETH_LDAP_BASE_DN: "${LDAP_BASEDN}"
  SHIBBOLETH_LDAP_USER: "${SHIBBOLETH_LDAP_USER}"
  SHIBBOLETH_API_KEYS: "1234567890"
  SHIBBOLETH_LDAP_PORT: "${SHIBBOLETH_LDAP_PORT}"
  SP_DOMAIN: "${SHIB_ADDRESS}"
  IDP_DOMAIN: "${SHIB_IDP_ADDRESS}"
  MPM_STARTSERVERS: "${SHIBBOLETH_SP_MPM_STARTSERVERS}"
  MPM_MINSPARETHREADS: "${SHIBBOLETH_SP_MPM_MINSPARETHREADS}"
  MPM_MAXSPARETHREADS: "${SHIBBOLETH_SP_MPM_MAXSPARETHREADS}"
  MPM_THREADLIMIT: "${SHIBBOLETH_SP_MPM_THREADLIMIT}"
  MPM_THREADSPERCHILD: "${SHIBBOLETH_SP_MPM_THREADSPERCHILD}"
  MPM_MAXREQUESTWORKERS: "${SHIBBOLETH_SP_MPM_MAXREQUESTWORKERS}"
  MPM_MAXCONNECTIONSPERCHILD: "${SHIBBOLETH_SP_MPM_MAXCONNECTIONSPERCHILD}"
  MEMCACHE_ENDPOINT: "${SHIBBOLETH_MEMCACHE_ENDPOINT}"
  SHIB_IDP_ADDRESS: "${SHIB_IDP_ADDRESS}"