kind: ConfigMap
apiVersion: v1
metadata:
  name: web-config
data:
  SPRING_APPLICATION_JSON: '{"logout":{"url": "https://localhost/Logout/"}}'
  IFS_WEB_GOOGLEANALYTICS_TRACKINGID: ""
  IFS_WEB_SYSTEM_USER_UID: "c0d02979-e66e-11e7-ac43-0242ac120002"
  IFS_WEB_REST_CONNECTIONS_MAX_TOTAL: "1000"
  IFS_WEB_REST_CONNECTIONS_MAX_PER_ROUTE: "1000"
  IFS_WEB_AJP_CONNECTIONS_MAX_TOTAL: "700"
  IFS_WEB_AJP_CONNECTIONS_ACCEPT_COUNT: "700"
  IFS_WEB_AJP_CONNECTIONS_MAX_THREADS: "300"
  IFS_LIVE_PROJECTS_LANDING_PAGE_URL: "localhost"
  IFS_EARLY_METRICS_URL: "localhost"
  IFS_WEB_BASEURL: 'https://localhost'
  IFS_SHOW_COVID_QUESTIONNAIRE_LINKS: 'localhost'
  IFS_WEB_VIRTUALASSISTANT_BOTSECRET: '123456'
  IFS_WEB_VIRTUALASSISTANT_BOTID: 'bot_id-dev'
  IFS_LOANS_SALESFORCE_PAGE_URL: "https://loans-innovateuk.cs80.force.com/loansCommunity/s"