apiVersion: apps/v1
kind: Deployment
metadata:
  name: registration-svc
spec:
  template:
    spec:
      containers:
        - name: spring-boot-service-container
          env:
          - name: SHIBBOLETH_LDAP_REQUIREVALIDPPOLICY
            value: "false"
