kind: ConfigMap
apiVersion: v1
metadata:
  name: shibboleth-config
data:
  SHIBBOLETH_LDAP_BASE_DN: "dc=nodomain"
  SHIBBOLETH_LDAP_USER: "cn=admin,dc=nodomain"
  SHIBBOLETH_API_KEYS: "1234567890"
  SHIBBOLETH_LDAP_PORT: "8389"
  SP_DOMAIN: "openshiftEnvKey.apps.org-env-0.org.innovateuk.ukri.org"
  IDP_DOMAIN: "auth-openshiftEnvKey.apps.org-env-0.org.innovateuk.ukri.org"
  MPM_STARTSERVERS: "2"
  MPM_MINSPARETHREADS: "25"
  MPM_MAXSPARETHREADS: "75"
  MPM_THREADLIMIT: "64"
  MPM_THREADSPERCHILD: "25"
  MPM_MAXREQUESTWORKERS: "150"
  MPM_MAXCONNECTIONSPERCHILD: "0"
  MEMCACHE_ENDPOINT: ""